core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [ 
    path('', views.home, name='home'),
    path('blog/', views.blog, name='blog'),
    path('blog/<language>', views.blog_language, name='language'),
    path('blog/post/<slug>', views.blog_post, name='posts'),
]

portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('core.urls', namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.db.models.fields import TextField
from django.shortcuts import reverse
from ckeditor.fields import RichTextField


class Blog(models.Model):

    LANGUAGES_CHOICES = (
    ('python', 'P'),
    ('django', 'D'),
    ('javascript', 'J'),
    ('react', 'R'),
    ('other', 'O'),
    )

    title = models.CharField(max_length=50)
    description = TextField(max_length=200)
    body = RichTextField(blank=True, null=True)
    language = models.CharField(choices=LANGUAGES_CHOICES, max_length=50)
    slug = models.SlugField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        """ Return a string representation of Blog """
        return self.title

    def get_absolute_url(self):
        return reverse("core:posts", kwargs={"slug": self.slug})

    def get_language_url(self):
        return reverse("core:language", kwargs={"language": self.language})
    

core/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout

class ContactForm(forms.Form):
    contact_name = forms.CharField(label='Nome',required=True)
    contact_email = forms.EmailField(label='Email',required=True)
    message = forms.CharField(label='Mensagem',
        required=True,
        widget=forms.Textarea
    )
    
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_class = 'form-control col-lg'
        self.helper.label_class = 'form-label'
        self.helper.layout = Layout(
            'contact_name',
            'contact_email',
            'message',
        )

core/views.py
from django.shortcuts import render, redirect
import requests
from .forms import ContactForm
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.http import HttpResponse
from django.core.mail import send_mail, BadHeaderError
from .models import Blog


def home(request):
    """ 
    Home Page

    GET API GitHub
    1) repos per page = 5
    2) sorted by last updated
    """
    response = requests.get('https://api.github.com/users/depotterdev/repos?per_page=5&sort=updated')
    repo = response.json()

    # Project Section
    projects = requests.get('https://api.github.com/users/DePotterDev/repos?sort=created&direction=asc')
    project = projects.json()

    """ Contact Form """
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = request.POST['contact_name']
            from_email = request.POST['contact_email']
            message = request.POST['message']
            html_message = render_to_string('contact_template.txt', {'from_email': from_email, 'message': message, 'subject': subject})
            plain_message = strip_tags(html_message)
            try:
                send_mail('Message from : ' + subject, plain_message, from_email, ['depotter.laurens@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('/')

    context = {'repo': repo, 'project': project, 'range': range(4), 'form': ContactForm}
    return render(request, 'home.html', context)


def blog(request):
    """ Blog """
    blog = Blog.objects.order_by('-updated_at')
    # FILTER OPTIONS ON LANGUAGES
    python_count = Blog.objects.filter(language='python').count()
    javascript_count = Blog.objects.filter(language='javascript').count()
    react_count = Blog.objects.filter(language='react').count()
    django_count = Blog.objects.filter(language='django').count()
    other_count = Blog.objects.filter(language='other').count()
    python = Blog.objects.filter(language='python')
    javascript = Blog.objects.filter(language='javascript')
    react = Blog.objects.filter(language='react')
    django = Blog.objects.filter(language='django')
    other = Blog.objects.filter(language='other')

    latest = Blog.objects.order_by('-created_at')[:5]

    context = {
        'blogs': blog,
        'python': python,
        'javascript': javascript,
        'react': react,
        'django': django,
        'other': other,
        'pc': python_count,
        'jc': javascript_count,
        'rc': react_count,
        'dc': django_count,
        'oc': other_count,
        'latest': latest
        }
    return render(request, 'blog.html', context)


def blog_language(request, language):
    """ Filter blog posts on language """
    blog = Blog.objects.filter(language=language)
    current_language = language
    # FILTER OPTIONS ON LANGUAGES
    python_count = Blog.objects.filter(language='python').count()
    javascript_count = Blog.objects.filter(language='javascript').count()
    react_count = Blog.objects.filter(language='react').count()
    django_count = Blog.objects.filter(language='django').count()
    other_count = Blog.objects.filter(language='other').count()
    python = Blog.objects.filter(language='python')
    javascript = Blog.objects.filter(language='javascript')
    react = Blog.objects.filter(language='react')
    django = Blog.objects.filter(language='django')
    other = Blog.objects.filter(language='other')

    latest = Blog.objects.order_by('-created_at')[:5]

    context = {
        'language': current_language,
        'blogs': blog,
        'python': python,
        'javascript': javascript,
        'react': react,
        'django': django,
        'other': other,
        'pc': python_count,
        'jc': javascript_count,
        'rc': react_count,
        'dc': django_count,
        'oc': other_count,
        'latest': latest
        }
    return render(request, 'blog-language.html', context)


def blog_post(request, slug):
    """ Blog Post """
    post = Blog.objects.get(slug=slug)

    # FILTER OPTIONS ON LANGUAGES
    python_count = Blog.objects.filter(language='python').count()
    javascript_count = Blog.objects.filter(language='javascript').count()
    react_count = Blog.objects.filter(language='react').count()
    django_count = Blog.objects.filter(language='django').count()
    other_count = Blog.objects.filter(language='other').count()
    python = Blog.objects.filter(language='python')
    javascript = Blog.objects.filter(language='javascript')
    react = Blog.objects.filter(language='react')
    django = Blog.objects.filter(language='django')
    other = Blog.objects.filter(language='other')

    latest = Blog.objects.order_by('-created_at')[:5]

    context = {
        'post': post,
        'python': python,
        'javascript': javascript,
        'react': react,
        'django': django,
        'other': other,
        'pc': python_count,
        'jc': javascript_count,
        'rc': react_count,
        'dc': django_count,
        'oc': other_count,
        'latest': latest
        }
    return render(request, 'blog-post.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/prism.css' %}">
    <title>Laurens de Potter</title>
</head>

<body>
    {% include "navbar-home.html" %}
    {% block content %}
    {% endblock content %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/prism.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
    {% include "footer.html" %}
</body>

</html>

templates/blog-language.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    {% include 'filter.html' %}
<!--BLOG SECTION-->
        <div class="col-9 p-4">
            <h4 class="display-1">Blog: <span class="{{language}}">{{language|capfirst}}</span></h4>
            <p>This little blog contains documentation, cheatsheets and short tutorials<br>
            on technologies I am currently working with.</p>

<!--BLOG POSTS-->
            <div class="mt-5">
                <div class="row">
                {% for blog in blogs %}
                    <div class="col-4 p-2">                    
                        <div class="card" style="height:200px;">
                            <a href="{{blog.get_absolute_url}}">
                                <div class="card-body bg-green">
                                    <h5 class="card-title">{{blog.title}}</h5>
                                    <p class="card-text mb-3">{{blog.description|truncatechars:150}}</p>
                                    <a href="#" class="{{blog.language}}">{{blog.language|capfirst}}</a>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}
                </div>

                <div class="mt-5">
                    <nav aria-label="Page navigation">
                        <ul class="pagination justify-content-center">
                            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link" href="#">Next</a></li>
                        </ul>
                    </nav>
                </div>

            </div>
<!--END BLOG POSTS-->
    </div>
</div>

{% endblock content %}

templates/blog-post.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    {% include 'filter.html' %}
<!--BLOG SECTION-->
        <div class="col-9 p-5">
<!--BREADCRUMBS-->
                <nav class="mb-5" aria-label="breadcrumb" style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Blog</a></li>
                    <li class="breadcrumb-item"><a href="#">{{post.language}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{post.title}}</li>
                </ol>
            </nav>
            <h1 class="display-1 mb-3">{{post.title}}</h1>
            <p>{{post.description}}</p>
            <p class="text-muted mb-5">
            {% if post.updated_at|time:"H\h i\m" != post.created_at|time:"H\h i\m" %}
            Created: {{post.created_at}}<br>
            Last updated: {{post.updated_at}}
            {% else %}
            Created: {{post.created_at}}<br>
            {% endif %}

            </p>            
            <p class="pe-5 me-5">
            {{post.body|safe}}
            </p>
        </div>  
</div>

{% endblock content %}

templates/blog.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
<!--FILTER OPTIONS-->
{% include 'filter.html' %}
<!--BLOG SECTION-->
        <div class="col-9 p-4">
            <h4 class="display-1">Blog</h4>
            <p>This little blog contains documentation, cheatsheets and short tutorials<br>
            on technologies I am currently working with.</p>

<!--BLOG POSTS-->
            <div class="mt-5">
                <div class="row">
                {% for blog in blogs %}
                    <div class="col-4 p-2">                    
                        <div class="card" style="height:200px;">
                            <a href="{{blog.get_absolute_url}}">
                                <div class="card-body bg-green">
                                    <h5 class="card-title">{{blog.title}}</h5>
                                    {% autoescape on %}
                                    <p class="card-text mb-3">{{blog.description|truncatechars:150}}</p>
                                    {% endautoescape %}
                                    <a href="#" class="{{blog.language}}">{{blog.language|capfirst}}</a>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}
                </div>

                <div class="mt-5">
                    <nav aria-label="Page navigation">
                        <ul class="pagination justify-content-center">
                            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link" href="#">Next</a></li>
                        </ul>
                    </nav>
                </div>

            </div>
<!--END BLOG POSTS-->
    </div>
</div>

{% endblock content %}

templates/filter.html
<div class="col-3 bg-gray p-5">
<!--TOPIC BUTTONS-->
    <h4 class="mb-3">Topics</h4>
        <a href="{% url 'core:language' language='python' %}" class="btn btn-python m-1">
            Python<span class="badge bg-light ms-1 text-dark">{{pc}}</span>
        </a>
        <a href="{% url 'core:language' language='django' %}" class="btn btn-django m-1">
            Django<span class="badge bg-light ms-1 text-dark">{{dc}}</span>
        </a>
        <a href="{% url 'core:language' language='javascript' %}" class="btn btn-javascript m-1">
            JavaScript<span class="badge bg-light ms-1 text-dark">{{jc}}</span>
        </a>
        <a href="{% url 'core:language' language='react' %}" class="btn btn-react m-1">
            React.js<span class="badge bg-light ms-1 text-dark">{{rc}}</span>
        </a>
        <a href="{% url 'core:language' language='other' %}" class="btn btn-other m-1">
            Other<span class="badge bg-light ms-1 text-dark">{{oc}}</span>
        </a>
<!--LATEST BLOG POSTS ADDED-->
    <h4 class="mt-5 mb-3">Latest Added</h4>
    <ul class="mb-5">
    {% for x in latest %}
        <li><a href="{{x.get_absolute_url}}"><span class="link">>_</span>{{x}}</a></li>
    {% endfor %}
    </ul>
<!--SECTION-->
    <a data-bs-toggle="collapse" href="#python" role="button" aria-expanded="false" aria-controls="python"><h5>Python</h5></a>
    <div class="collapse" id="python">
        <ul>
            {% for x in python %}
            <li><a href="{{x.get_absolute_url}}">{{x}}</a></li>
            {% endfor %}
        </ul>
    </div>
    <a data-bs-toggle="collapse" href="#django" role="button" aria-expanded="false" aria-controls="django"><h5>Django</h5></a>
    <div class="collapse" id="django">
        <ul>
        {% for x in django %}
            <li><a href="{{x.get_absolute_url}}">{{x}}</a></li>
        {% endfor %}
        </ul>    
    </div>
    <a data-bs-toggle="collapse" href="#javascript" role="button" aria-expanded="false" aria-controls="javascript"><h5>JavaScript</h5></a>
    <div class="collapse" id="javascript">
        <ul>
        {% for x in javascript %}
            <li><a href="{{x.get_absolute_url}}">{{x}}</a></li>
        {% endfor %}
        </ul>      
    </div>

    <a data-bs-toggle="collapse" href="#react" role="button" aria-expanded="false" aria-controls="react"><h5>React</h5></a>
    <div class="collapse" id="react">
        <ul>
        {% for x in react  %}
            <li><a href="{{x.get_absolute_url}}">{{x}}</a></li>
        {% endfor %}
        </ul>    
    </div>
</div>

templates/footer.html
<footer class="bg-darkgreen py-5">
<div class="row">
    <div class="col-4">
        <h5 class="text-center py-5 lead text-light">Hosted on Ubuntu 20.04,<br> by Digitalocean</h5>
    </div>
    <div class="col-4">
        <h4 class="color-green text-center py-5">Made with <span class="text-light">Django</span></h4>
    </div>
    <div class="col-4">
    <div class="d-flex justify-content-center">
        <div >
            <a href="https://www.linkedin.com/in/laurens-de-potter/"><h5 class=" pt-5 lead text-light">>_ Visit my Linkedin</h5></a>
            <a href="https://github.com/DePotterDev"><h5 class="lead text-light">>_ Visit my GitHub</h5></a>
            <a href="https://www.hackerrank.com/depotter_laurens"><h5 class="pb-5 lead text-light">>_ Visit my HackerRank</h5></a>
        </div>
    </div>
    
    </div>

</div>

    

</footer>

templates/navbar-home.html
{% load static %}

{% block nav %}

<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top border-bottom">
  <div class="container">
    <a class="navbar-brand" href="{% url 'core:home' %}">DePotter</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      {% if request.path == '/' %}
        <li class="nav-item">{% block nav-skills %}<a class="nav-link" aria-current="page" href="#skills">Habilidades</a>{% endblock nav-skills %}
        </li>
        <li class="nav-item">{% block nav-project %}<a class="nav-link" href="#projects">Projetos</a>{% endblock nav-project %}
        </li>
        <li class="nav-item dropdown">{% block nav-about %}<a class="nav-link" href="#about_section">Sobre</a>{% endblock nav-about %}
        </li>
          {% endif %}
        <li class="nav-item">{% block nav-blog %}<a class="nav-link" href="{% url 'core:blog' %}">Blog</a>
        {% endblock nav-blog %}</li>
        <li class="nav-item">
        {% if request.path == '/' %}
          {% block contact %}
            <a class="nav-link" href="#contact">Contato</a>
          {% endblock contact %}
        {% endif %}
        </li>
      </ul>
      <div class="d-flex">
        <a class="d-flex align-items-center" href="https://www.linkedin.com/in/laurens-de-potter/" target="_blank">
          <span class="icon icon-linkedin me-3">
          </span>
        </a>

        <a class="d-flex align-items-center" href="http://github.com/depotterdev" target="_blank">
          <span class="icon icon-github me-3">
          </span>
        </a> 

        <a href="{% static 'files/Resume-Laurens-de-Potter.pdf' %}" id="resume" class="btn btn-outline-success" target="_blank">
          Currículo
        </a>  
      </div>
    </div>
  </div>
</nav>
{% endblock nav %}